import React, { useRef, useState } from 'react';
import { Download, Copy, Check, RefreshCw, BookOpenCheck } from 'lucide-react';
import { GeneratedStory, StoryLanguage } from '../types';

interface StoryDisplayProps {
  story: GeneratedStory | null;
  onReset: () => void;
  language: StoryLanguage;
}

const StoryDisplay: React.FC<StoryDisplayProps> = ({ story, onReset, language }) => {
  const [copied, setCopied] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  if (!story) return null;

  const handleCopy = async () => {
    if (!story.content) return;
    try {
      await navigator.clipboard.writeText(story.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy!', err);
    }
  };

  const handleDownload = () => {
    if (!story.content) return;
    const blob = new Blob([story.content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${story.title.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'generated_story'}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  // Determine text direction based on language
  const isRTL = language === StoryLanguage.URDU;

  return (
    <div className="animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="bg-white/5 backdrop-blur-lg border border-white/10 rounded-2xl shadow-xl overflow-hidden flex flex-col h-full">
        {/* Header Actions */}
        <div className="flex items-center justify-between p-4 border-b border-white/10 bg-black/20">
          <div className="flex items-center gap-2 text-magic-300">
            <BookOpenCheck className="w-5 h-5" />
            <span className="text-sm font-semibold uppercase tracking-wider">Story Result</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="p-2 hover:bg-white/10 rounded-lg transition-colors text-gray-300 hover:text-white"
              title="Copy to clipboard"
            >
              {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
            </button>
            <button
              onClick={handleDownload}
              className="p-2 hover:bg-white/10 rounded-lg transition-colors text-gray-300 hover:text-white"
              title="Download as .txt"
            >
              <Download className="w-4 h-4" />
            </button>
            <div className="w-px h-4 bg-white/20 mx-1"></div>
            <button
              onClick={onReset}
              className="p-2 hover:bg-white/10 rounded-lg transition-colors text-gray-300 hover:text-white group"
              title="Create New Story"
            >
              <RefreshCw className="w-4 h-4 group-hover:rotate-180 transition-transform duration-500" />
            </button>
          </div>
        </div>

        {/* Story Content */}
        <div 
          ref={contentRef}
          className={`
            p-6 md:p-10 flex-grow overflow-y-auto max-h-[800px] 
            prose prose-invert prose-lg max-w-none
            ${isRTL ? 'text-right' : 'text-left'}
          `}
          dir={isRTL ? 'rtl' : 'ltr'}
        >
          {/* We assume the AI returns a title in the first few lines, but we can also display it explicitly if we parsed it separately. 
              Since the prompt asks for [TITLE] then [CONTENT], we can display raw text which preserves the AI's formatting. */}
          <div className="whitespace-pre-wrap leading-relaxed font-serif text-slate-200">
            {story.content}
          </div>
        </div>
        
        <div className="p-4 bg-black/20 border-t border-white/10 text-center text-xs text-gray-500">
          Generated by Gemini AI • {new Date(story.timestamp).toLocaleDateString()}
        </div>
      </div>
    </div>
  );
};

export default StoryDisplay;
